In [3]:
import numpy as np


# Ans1

In [2]:
#function to create columns of the output matrix which are powers of the input

def atv(N,vect):
    print(np.column_stack(vect**(N-i-1) for i in range(N)))

#Taking input
l=[]
ip= int(input("Enter the no of elemnts you want in the vector "))

for i in range(ip):
    l.append(int(input("Enter the "+str(i+1)+" element of the array ")))
    vect=np.array(l)

N=vect.size
atv(N,vect)


Enter the no of elemnts you want in the vector 4
Enter the 1 element of the array 1
Enter the 2 element of the array 2
Enter the 3 element of the array 3
Enter the 4 element of the array 4
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


<ipython-input-2-99177cb4dc3f>:4: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  print(np.column_stack(vect**(N-i-1) for i in range(N)))


# Ans 2

In [62]:
#Function to print moving averages
arr=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
l=[]
count=0
k=3
while count< (arr.size-k+1):
    avg=round(sum(arr[:k])/k,2)
    l.append(avg)
    arr=np.delete(arr,0)
    count+=1
print(l)

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67]
